### ISSUE TITLE
%(placeholder)s incorrect when translating to Chinese Characters

### ISSUE THREAD

**Issue by JustinWingChungHui** [ankitpopli1891/django-autotranslate#16]
When converting something like
` Hello %(placeholder)s`

To Chinese becomes:
`您好％（占位符）`

The `%` symbol becomes a different  Unicode character `％`. 
The `(` character also becomes a different Unicode character `（` .
Also sometimes the `s` disappears or moves.

And so this unfortunately fails at the `compilemessages` stage

**Comment by ankitpopli1891** [comment]
HI @JustinWingChungHui,

From the description it appears that the bug is related to [compilemessages](https://docs.djangoproject.com/en/1.10/ref/django-admin/#django-admin-compilemessages) & we can't do much about it.

Although, I would be interested in finding the root cause. It may take some time due to my other commitments.

**Comment by JustinWingChungHui** [comment]
It happens when it gets put through Google translate. `%` becomes `％` and `(` becomes `（` which are different Unicode characters.  

You can see what happens if you input `%(placeholder)s` on the online Google translate site.

So either compilemessages needs to also recognise these two other characters to denote a placeholder or django-autotranslate needs to do something clever (not sure what!) with the placeholder for Asian languages.

**Comment by ankitpopli1891** [comment]
Ah! I remember @generalov did some exceptional work & handled it [here](https://github.com/ankitpopli1891/django-autotranslate/blob/master/autotranslate/management/commands/translate_messages.py#L158).

Ran the tests with these strings:

```pot
#: test_project/settings.py:16
#, python-format
msgid "Hello %(placeholder)s"
msgstr "你好 %(placeholder)s"

#: test_project/urls.py:27
#, python-format
msgid "Hello %(World)s"
msgstr "你好，世界__"         <---------- 'World' got translated :/
```
There is definite need for improvement here. :+1: I'll try to work on the issue this weekend. 

Meanwhile, a PR is always welcomed :smile:
