### ISSUE TITLE
Can translate only from English

### ISSUE THREAD

**Issue by anufry** [ankitpopli1891/django-autotranslate#22]
In autotranslate/management/commands/translate_messages.py : 96 hardcoded 'en' as source_language.

Better set to settings.LANGUAGE_CODE or add own setting var for this app

**Comment by diogosimao** [comment]
What about using commands like this:

> $ python manage.py translate_messages -l 'de' -l 'es'

It's still fixed on '_en_'?

**Comment by ankitpopli1891** [comment]
Yep. Closing this as a dupe of #18 

I've not had a chance to work on it again!

I'm not sure when I'm gonna be able to work on it again!
