### ISSUE TITLE
Django autotranslate installation fails

### ISSUE THREAD

**Issue by iamonuwa** [ankitpopli1891/django-autotranslate#24]
I keep getting this error anytime I attempt to install the package. I'm trying to install it within a docker environment.

```pip3 install --upgrade -r test.txt```

It gives the error below
![image](https://user-images.githubusercontent.com/6551094/80742077-af016d80-8b12-11ea-865d-bbeb4ad03edb.png)

**Comment by mds1** [comment]
I'm having this same issue, but was not able to reproduce it locally in a virtual environment. It only occurred when following the instructions to build [this project](https://github.com/gitcoinco/web) with Docker.

I tried downgrading to older versions of django-autotranslate, as well as not specifying a version, and all approaches failed when building with Docker.

**Comment by iamonuwa** [comment]
I'm going to close this issue as the issue is beyond this. The error is coming from pip not this package.

**Comment by mds1** [comment]
@iamonuwa Ah got it, thanks. Have you figured out a solution/workaround to this?

**Comment by owocki** [comment]
ive got other swho are reportingthis too

```
ParsedRequirement' object has no attribute 'req
```

**Comment by owocki** [comment]
```
Collecting django-autotranslate==1.1.0
  Downloading django-autotranslate-1.1.0.tar.gz (8.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-05q5rnle/django-autotranslate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-05q5rnle/django-autotranslate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jfqeewod
         cwd: /tmp/pip-install-05q5rnle/django-autotranslate/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-05q5rnle/django-autotranslate/setup.py", line 25, in <module>
        requirements = [str(ir.req) for ir in install_requirements]
      File "/tmp/pip-install-05q5rnle/django-autotranslate/setup.py", line 25, in <listcomp>
        requirements = [str(ir.req) for ir in install_requirements]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip3 install --upgrade -r test.txt' returned a non-zero code: 1
```

so a workaround would be appreciated!

**Comment by octavioamu** [comment]
Seems related to this https://github.com/ankitpopli1891/django-autotranslate/pull/20 
but we already used django-autotranslate 1.1.0 that seems to be the version with that fix. So probably the issue you guys are having is related to the pip version installed, did you guys reinstalled the app recently on your local? I mean purging everything ? I trying to to guess this is some kind related to some new pip3 release, but is just a guess.

**Comment by iamonuwa** [comment]
> @iamonuwa Ah got it, thanks. Have you figured out a solution/workaround to this?

Yes, use a previous version of pip < 10.x. It should work.

**Comment by iamonuwa** [comment]
> Seems related to this https://github.com/ankitpopli1891/django-autotranslate/pull/20 
> but we already used django-autotranslate 1.1.0 that seems to be the version with that fix. So probably the issue you guys are having is related to the pip version installed, did you guys reinstalled the app recently on your local? I mean purging everything ? I trying to to guess this is some kind related to some new pip3 release, but is just a guess. 

I'm trying to get it working on a new machine and the error sprung up.
