### ISSUE TITLE
Efficient API Usage

### ISSUE THREAD

**Issue by emrahayanoglu** [ankitpopli1891/django-autotranslate#7]
Hello,

Currently, the library translates for each word within the po files. I think that it should check whether related message id is translated before or not. This helps us to improve the efficiency of using the Google Translate API.

**Comment by ankitpopli1891** [comment]
Hey @emrahayanoglu, can you please explain the issue with an example.

**Comment by emrahayanoglu** [comment]
I just made a brainstorming and something like following would be good for efficiency:
- We should keep the all of the message id and message values within all languages in newly created JSON or whatever file with last updated date. Format should be like that:
  
  ```
  [
   { 
     language:"en",
     msg_list: [{ 
                      msgid:'blablabla', 
                      msgvalue:'mahmahmah',
                      msgupdatedate:"02/11/2015 10:10 UTC" 
                    }]
   }
  ]
  ```
- Then, we check it from the JSON file whether the related message value on the related message id and specified language are changed or not.
- Furthermore, as google translate algorithm is updated frequently, it would be good to check whether message value is changed or not with looking at the updated date time. Such as:
  We should have a settings variable called 
  
  ```
  GOOGLE_TRANSLATE_UPDATE_DATE_PERIOD  = '15' #days
  ```

Then, we can check the message values if the updated dates are older than the update date period.

**Comment by ankitpopli1891** [comment]
That's a nice idea, would love to work on this. It will take me some time to implement this due to some other commitments.

Meanwhile, feel free to contribute ;) 

Thanks

**Comment by emrahayanoglu** [comment]
Ok, I'd like to conribute for this enhancement. Let's do it :)

You're welcome...

**Comment by ChillarAnand** [comment]
Any updates?

**Comment by emrahayanoglu** [comment]
Actually, I've done it on my local code, but didn't pull it. 

I'll make a pull request from @ankitpopli1891 .
