### ISSUE TITLE
Alternative Translation Service Backends

### ISSUE THREAD

**Issue by ankitpopli1891** [ankitpopli1891/django-autotranslate#8]
[Alternative to Google Translate API](http://stackoverflow.com/questions/6151668/alternative-to-google-translate-api)

**Comment by likeca** [comment]
use google translate web service.
url = 'https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl={}&&dt=t&q={}'.format('zh', 'hello world!')
